### ISSUE TITLE
Writing to Specific File

### ISSUE THREAD

**Issue by biocross** [simonlast/node-persist#103]
Is there away to specify exactly what the saved JSON file should be? Currently, specifying a **DIR** is possible, but what I noticed is a random `UDID` is generated to actually save the JSON.

Is there a way of specifying the exact file? Like `~/.myapp/config.json`

**Comment by akhoury** [comment]
Not really, we MD5-hash the filenames most importantly __to control the length of the keys__ and filter out invalid key names, since operating systems have a limit on file names length and invalid chars for the names.

Why do you need an exact name of the file? are you trying to read it in a different program?

node-persist is designed to write __and read__ for you, also we wrap any value you pass in with another top-level JSON that we add other stuff to, like, `ttl`

If you use it that way you never need to know what the exact filename actually is, you can also use `config.json` as a key if you prefer.

```javascript
await storage.setItem('config.json', { foo: 'bar' } );
let config = await storage.getItem('config.json');

```

**Comment by akhoury** [comment]
sure, if you want to give it a try,
