### ISSUE TITLE
File path issue.

### ISSUE THREAD

**Issue by jkarttunen** [simonlast/node-persist#48]
Seems like there is some relative file path issue

Where `node index.js ` console.logs getItem('foo') normally.

but `node foo/index.js` does not.

**Comment by jkarttunen** [comment]
Nevermind, using absolute path instead of relative seems to work fine. Maybe add to docs.

**Comment by akhoury** [comment]
hmm what's in index.js?

**Comment by schester44** [comment]
I came across this issue as well...

storage was empty even though the .node-persist/storage folder and files were present.

The issue was because I was starting the server with pm2 while using absolute paths instead of paths relative to node-persist

example: `pm2 start /srv/app/server.js` results in empty storage but `pm2 start ./server.js` does not...
