### ISSUE TITLE
Refactoring to use node-persist with async/await/Promise features of ES7

### ISSUE THREAD

**Issue by Jodes81** [simonlast/node-persist#75]
I hope this is not off-topic, I'd massively appreciate advice on this, don't know where else I could ask. 

I was hoping for some advice on refactoring code to get the most out of ES7. I have looked at many examples of async/await/Promise features, and think I understand them, yet I cannot wrap my head around how to transform my code. Extracts are as follows:

I have a (simplified) wrapper module for node-persist that contains:

```
var storage = require('node-persist');
var mydb = 
{
    isReady: false,
    init: function()
    {
        storage.init().then(function(){
            mydb.isReady = true;
        });
    },
    store: function(key, val, onDone)
    {
        if (!mydb.isReady){
            console.error("Store: storage is not up yet. (Tried to store '"+key+"':'"+val+"')");
        } else {
            storage.setItem(key, val).then(onDone);
        }
    },
    retrieve: function(key, onDone)
    {
        if (!mydb.isReady){
            console.error("Retrieve: storage is not up yet. (Tried to retrieve '"+key+"')");
        } else {
            storage.getItem(key).then(onDone);
        }
    },
    //...
}
mydb.init();
module.exports = mydb;
```

Then, for example, I use the above code to modify a key/value pair like so:

```
function incrementFoo(onDone){
    mydb.retrieve("myObjectKey", function(myObject){
        myObject.foo++;
        mydb.store("myObjectKey", myObject, function(){
            onDone();
        })
    });
}
```

It all quickly leads to the Pyramid of doom in the rest of my code as the above function shows - I'd be extremely grateful for any help!

**Comment by yusefnapora** [comment]
This is pretty simple, since node-persist already uses Promises.  Here's how I'd rewrite your example with async/await (not tested, but hopefully mostly correct):

```javascript
const mydb = {
  initialized: false,

  async getDB() {
    if (this.initialized) { return storage }
    await storage.init()
    this.initialized = true
    return storage
  },

  async store (key, val) {
    const db = await this.getDB()

    // the `await` here is important! we only want to return once the `setItem` Promise completes
    await db.setItem(key,val)  
  },

  async retrieve (key) {
    const db = await this.getDB()

    // async functions return Promises under the hood, so we can return the Promise from 
    // `db.getItem` directly instead of `await`ing on it and then returning the resolved value
    return db.getItem(key) 
  }
}

async function incrementFoo() {
  const myObject = await mydb.retrieve("myObjectKey")
  myObject.foo++
  await mydb.store("myObjectKey", myObject)
}
```

The main difference is the use of a `getDB` accessor that only returns the `storage` object after it's been initialized.  Then you don't need to check `isReady` in the `store` and `retrieve` methods; they'll always get an initialized db from `getDB`.  And of course, async/await makes waiting on Promises much more pleasant syntactically.

It's important to keep in mind that the `incrementFoo` function returns a `Promise`, so you need to either `await` it from inside another `async` function, or call e.g. `incrementFoo().then(() => { doSomethingWithFoo())`

Also, if your async operations can fail (and you should basically always assume that every operation can fail), you should wrap them in try/catch inside of an async function (or use e.g. `incrementFoo().catch(err => { doSomethingWithErrors(err) })`

Hope that helps 😄

**Comment by Jodes81** [comment]
Perfect! thank you so much!
